import type { MvzDocument } from '../core/mvz/types'

export interface Preset {
  id: string
  name: string
  nameEn: string
  category: 'junior' | 'senior'
  description: string
  descriptionEn: string
  doc: MvzDocument
}

export const presets: Preset[] = [
  {
    id: 'coordinate-system',
    name: '平面直角坐标系',
    nameEn: 'Coordinate System',
    category: 'junior',
    description: '基础坐标系与四个象限',
    descriptionEn: 'Basic coordinate system',
    doc: {
      version: '1.0',
      viewport: { xmin: -6, xmax: 6, ymin: -5, ymax: 5 },
      elements: [
        { id: 'O', type: 'point', x: 0, y: 0, label: 'O', draggable: false },
        { id: 'X', type: 'point', x: 5, y: 0, label: 'x', draggable: false },
        { id: 'Y', type: 'point', x: 0, y: 5, label: 'y', draggable: false },
        { id: 'xAxis', type: 'line', through: ['O', 'X'], color: '#3A3A3C' },
        { id: 'yAxis', type: 'line', through: ['O', 'Y'], color: '#3A3A3C' },
        { id: 'P', type: 'point', x: 3, y: 2, label: 'P(3,2)', draggable: true },
      ],
      annotations: [{ type: 'label', at: 'P', label: 'P(3,2)' }],
    },
  },
  {
    id: 'linear-function',
    name: '一次函数',
    nameEn: 'Linear Function',
    category: 'junior',
    description: 'y = 2x - 1',
    descriptionEn: 'y = 2x - 1',
    doc: {
      version: '1.0',
      viewport: { xmin: -5, xmax: 5, ymin: -5, ymax: 5 },
      elements: [
        { id: 'A', type: 'point', x: 0, y: -1, label: 'A', draggable: true },
        { id: 'B', type: 'point', x: 2, y: 3, label: 'B', draggable: true },
        { id: 'AB', type: 'segment', between: ['A', 'B'] },
      ],
      functions: [{
        id: 'f1',
        expr: '2*x - 1',
        color: '#1C1C1E',
        bind: { mode: 'linear', points: ['A', 'B'] },
      }],
    },
  },
  {
    id: 'triangle-basic',
    name: '三角形',
    nameEn: 'Triangle',
    category: 'junior',
    description: '基础三角形 ABC',
    descriptionEn: 'Basic triangle ABC',
    doc: {
      version: '1.0',
      viewport: { xmin: -1, xmax: 7, ymin: -1, ymax: 6 },
      elements: [
        { id: 'A', type: 'point', x: 1, y: 1, label: 'A', draggable: true },
        { id: 'B', type: 'point', x: 5, y: 1, label: 'B', draggable: true },
        { id: 'C', type: 'point', x: 3, y: 4, label: 'C', draggable: true },
        { id: 'tri', type: 'polygon', vertices: ['A', 'B', 'C'] },
      ],
    },
  },
  {
    id: 'triangle-altitudes',
    name: '三角形的三条高',
    nameEn: 'Triangle Altitudes',
    category: 'junior',
    description: '含三条高的辅助线',
    descriptionEn: 'Three altitudes with auxiliary lines',
    doc: {
      version: '1.0',
      viewport: { xmin: -1, xmax: 7, ymin: -1, ymax: 6 },
      elements: [
        { id: 'A', type: 'point', x: 1, y: 1, label: 'A', draggable: true },
        { id: 'B', type: 'point', x: 5, y: 1, label: 'B', draggable: true },
        { id: 'C', type: 'point', x: 3, y: 4, label: 'C', draggable: true },
        { id: 'tri', type: 'polygon', vertices: ['A', 'B', 'C'] },
        { id: 'hA', type: 'perpendicular', from: 'A', to: 'BC', auxiliary: true, style: 'dashed' },
        { id: 'hB', type: 'perpendicular', from: 'B', to: 'AC', auxiliary: true, style: 'dashed' },
        { id: 'hC', type: 'perpendicular', from: 'C', to: 'AB', auxiliary: true, style: 'dashed' },
      ],
    },
  },
  {
    id: 'triangle-medians',
    name: '三角形的中线',
    nameEn: 'Triangle Medians',
    category: 'junior',
    description: '三条中线与重心',
    descriptionEn: 'Medians and centroid',
    doc: {
      version: '1.0',
      viewport: { xmin: -1, xmax: 7, ymin: -1, ymax: 6 },
      elements: [
        { id: 'A', type: 'point', x: 1, y: 1, label: 'A', draggable: true },
        { id: 'B', type: 'point', x: 5, y: 1, label: 'B', draggable: true },
        { id: 'C', type: 'point', x: 3, y: 4, label: 'C', draggable: true },
        { id: 'tri', type: 'polygon', vertices: ['A', 'B', 'C'] },
        { id: 'mAB', type: 'midpoint', of: ['A', 'B'], label: 'M', auxiliary: true },
        { id: 'mBC', type: 'midpoint', of: ['B', 'C'], label: 'N', auxiliary: true },
        { id: 'mAC', type: 'midpoint', of: ['A', 'C'], label: 'P', auxiliary: true },
        { id: 'medA', type: 'segment', between: ['C', 'mAB'], auxiliary: true, style: 'dashed' },
        { id: 'medB', type: 'segment', between: ['A', 'mBC'], auxiliary: true, style: 'dashed' },
        { id: 'medC', type: 'segment', between: ['B', 'mAC'], auxiliary: true, style: 'dashed' },
      ],
    },
  },
  {
    id: 'triangle-bisectors',
    name: '三角形的角平分线',
    nameEn: 'Angle Bisectors',
    category: 'junior',
    description: '三条角平分线',
    descriptionEn: 'Three angle bisectors',
    doc: {
      version: '1.0',
      viewport: { xmin: -1, xmax: 7, ymin: -1, ymax: 6 },
      elements: [
        { id: 'A', type: 'point', x: 1, y: 1, label: 'A', draggable: true },
        { id: 'B', type: 'point', x: 5, y: 1, label: 'B', draggable: true },
        { id: 'C', type: 'point', x: 3, y: 4, label: 'C', draggable: true },
        { id: 'tri', type: 'polygon', vertices: ['A', 'B', 'C'] },
        { id: 'bisA', type: 'angleBisector', vertex: 'A', arm1: 'B', arm2: 'C', auxiliary: true, style: 'dashed' },
        { id: 'bisB', type: 'angleBisector', vertex: 'B', arm1: 'A', arm2: 'C', auxiliary: true, style: 'dashed' },
        { id: 'bisC', type: 'angleBisector', vertex: 'C', arm1: 'A', arm2: 'B', auxiliary: true, style: 'dashed' },
      ],
    },
  },
  {
    id: 'pythagorean',
    name: '勾股定理',
    nameEn: 'Pythagorean Theorem',
    category: 'junior',
    description: '直角三角形 a²+b²=c²',
    descriptionEn: 'Right triangle a²+b²=c²',
    doc: {
      version: '1.0',
      viewport: { xmin: -1, xmax: 6, ymin: -1, ymax: 5 },
      elements: [
        { id: 'A', type: 'point', x: 0, y: 0, label: 'A', draggable: true },
        { id: 'B', type: 'point', x: 4, y: 0, label: 'B', draggable: true },
        { id: 'C', type: 'point', x: 0, y: 3, label: 'C', draggable: true },
        { id: 'tri', type: 'polygon', vertices: ['A', 'B', 'C'] },
        { id: 'h', type: 'perpendicular', from: 'C', to: 'AB', auxiliary: true, style: 'dashed' },
      ],
      annotations: [{ type: 'angle', points: ['C', 'A', 'B'], label: '90°' }],
    },
  },
  {
    id: 'circle-basic',
    name: '圆与圆心',
    nameEn: 'Circle',
    category: 'junior',
    description: '圆心 O 与半径',
    descriptionEn: 'Circle with center and radius',
    doc: {
      version: '1.0',
      viewport: { xmin: -5, xmax: 5, ymin: -5, ymax: 5 },
      elements: [
        { id: 'O', type: 'point', x: 0, y: 0, label: 'O', draggable: true },
        { id: 'P', type: 'point', x: 3, y: 0, label: 'P', draggable: true },
        { id: 'c', type: 'circle', center: 'O', through: 'P' },
        { id: 'r', type: 'segment', between: ['O', 'P'], auxiliary: true, style: 'dashed' },
      ],
    },
  },
  {
    id: 'circle-angle',
    name: '圆心角与圆周角',
    nameEn: 'Central & Inscribed Angles',
    category: 'junior',
    description: '同弧所对圆心角与圆周角',
    descriptionEn: 'Central and inscribed angles',
    doc: {
      version: '1.0',
      viewport: { xmin: -5, xmax: 5, ymin: -5, ymax: 5 },
      elements: [
        { id: 'O', type: 'point', x: 0, y: 0, label: 'O', draggable: false },
        { id: 'A', type: 'point', x: 3, y: 0, label: 'A', draggable: true },
        { id: 'B', type: 'point', x: 0, y: 3, label: 'B', draggable: true },
        { id: 'C', type: 'point', x: -2, y: 2, label: 'C', draggable: true },
        { id: 'c', type: 'circle', center: 'O', through: 'A' },
        { id: 'OA', type: 'segment', between: ['O', 'A'] },
        { id: 'OB', type: 'segment', between: ['O', 'B'] },
        { id: 'CA', type: 'segment', between: ['C', 'A'], auxiliary: true, style: 'dashed' },
        { id: 'CB', type: 'segment', between: ['C', 'B'], auxiliary: true, style: 'dashed' },
      ],
      annotations: [
        { type: 'angle', points: ['A', 'O', 'B'], label: '∠AOB' },
        { type: 'angle', points: ['A', 'C', 'B'], label: '∠ACB' },
      ],
    },
  },
  {
    id: 'quadratic',
    name: '二次函数',
    nameEn: 'Quadratic Function',
    category: 'senior',
    description: 'y = x² - 2x - 3',
    descriptionEn: 'y = x² - 2x - 3',
    doc: {
      version: '1.0',
      viewport: { xmin: -5, xmax: 5, ymin: -6, ymax: 4 },
      elements: [
        { id: 'V', type: 'point', x: 1, y: -4, label: '顶点', draggable: true },
        { id: 'r1', type: 'point', x: -1, y: 0, label: 'x₁', draggable: true },
        { id: 'r2', type: 'point', x: 3, y: 0, label: 'x₂', draggable: true },
      ],
      functions: [{
        id: 'f1',
        expr: 'x^2 - 2*x - 3',
        color: '#1C1C1E',
        bind: { mode: 'quadratic_vertex_roots', vertex: 'V', roots: ['r1', 'r2'] },
      }],
      annotations: [{ type: 'label', at: 'V', label: '(1,-4)' }],
    },
  },
  {
    id: 'quadratic-roots',
    name: '二次函数与判别式',
    nameEn: 'Quadratic & Discriminant',
    category: 'senior',
    description: '抛物线与 x 轴交点',
    descriptionEn: 'Parabola and x-intercepts',
    doc: {
      version: '1.0',
      viewport: { xmin: -5, xmax: 5, ymin: -6, ymax: 4 },
      elements: [
        { id: 'r1', type: 'point', x: -1, y: 0, label: 'x₁', draggable: true },
        { id: 'r2', type: 'point', x: 3, y: 0, label: 'x₂', draggable: true },
        { id: 'V', type: 'point', x: 1, y: -4, label: 'V', draggable: true },
      ],
      functions: [{
        id: 'f1',
        expr: 'x^2 - 2*x - 3',
        color: '#1C1C1E',
        bind: { mode: 'quadratic_vertex_roots', vertex: 'V', roots: ['r1', 'r2'] },
      }],
    },
  },
  {
    id: 'trig-sin',
    name: '正弦函数',
    nameEn: 'Sine Function',
    category: 'senior',
    description: 'y = sin(x)',
    descriptionEn: 'y = sin(x)',
    doc: {
      version: '1.0',
      viewport: { xmin: -7, xmax: 7, ymin: -2, ymax: 2 },
      elements: [],
      functions: [
        { id: 'f1', expr: 'sin(x)', color: '#1C1C1E' },
        { id: 'f2', expr: 'cos(x)', color: '#8E8E93' },
      ],
    },
  },
  {
    id: 'ellipse',
    name: '椭圆',
    nameEn: 'Ellipse',
    category: 'senior',
    description: '椭圆 x²/9 + y²/4 = 1',
    descriptionEn: 'Ellipse x²/9 + y²/4 = 1',
    doc: {
      version: '1.0',
      viewport: { xmin: -5, xmax: 5, ymin: -3, ymax: 3 },
      elements: [
        { id: 'O', type: 'point', x: 0, y: 0, label: 'O', draggable: true },
        { id: 'A', type: 'point', x: 3, y: 0, label: 'A', draggable: true },
        { id: 'B', type: 'point', x: 0, y: 2, label: 'B', draggable: true },
      ],
      functions: [
        {
          id: 'f1',
          expr: 'ellipse_upper',
          bind: { mode: 'ellipse', center: 'O', major: 'A', minor: 'B', branch: 'upper' },
        },
        {
          id: 'f2',
          expr: 'ellipse_lower',
          bind: { mode: 'ellipse', center: 'O', major: 'A', minor: 'B', branch: 'lower' },
        },
      ],
    },
  },
  {
    id: 'hyperbola',
    name: '双曲线',
    nameEn: 'Hyperbola',
    category: 'senior',
    description: '双曲线 x²/4 - y²/9 = 1',
    descriptionEn: 'Hyperbola x²/4 - y²/9 = 1',
    doc: {
      version: '1.0',
      viewport: { xmin: -6, xmax: 6, ymin: -5, ymax: 5 },
      elements: [
        { id: 'O', type: 'point', x: 0, y: 0, label: 'O', draggable: true },
        { id: 'V', type: 'point', x: 2, y: 0, label: 'V', draggable: true },
        { id: 'C', type: 'point', x: 0, y: 3, label: 'C', draggable: true },
      ],
      functions: [
        {
          id: 'f1',
          expr: 'hyperbola_ru',
          bind: { mode: 'hyperbola', center: 'O', vertex: 'V', conjugate: 'C', branch: 'ru' },
        },
        {
          id: 'f2',
          expr: 'hyperbola_rd',
          bind: { mode: 'hyperbola', center: 'O', vertex: 'V', conjugate: 'C', branch: 'rd' },
        },
        {
          id: 'f3',
          expr: 'hyperbola_lu',
          bind: { mode: 'hyperbola', center: 'O', vertex: 'V', conjugate: 'C', branch: 'lu' },
        },
        {
          id: 'f4',
          expr: 'hyperbola_ld',
          bind: { mode: 'hyperbola', center: 'O', vertex: 'V', conjugate: 'C', branch: 'ld' },
        },
      ],
    },
  },
  {
    id: 'parabola-conic',
    name: '抛物线（圆锥曲线）',
    nameEn: 'Parabola (Conic)',
    category: 'senior',
    description: 'y = x²/4',
    descriptionEn: 'y = x²/4',
    doc: {
      version: '1.0',
      viewport: { xmin: -5, xmax: 5, ymin: -1, ymax: 6 },
      elements: [
        { id: 'V', type: 'point', x: 0, y: 0, label: 'V', draggable: true },
        { id: 'P', type: 'point', x: 2, y: 1, label: 'P', draggable: true },
      ],
      functions: [{
        id: 'f1',
        expr: 'x^2/4',
        color: '#1C1C1E',
        bind: { mode: 'quadratic_vertex', vertex: 'V', through: 'P' },
      }],
    },
  },
  {
    id: 'vector-add',
    name: '向量加法',
    nameEn: 'Vector Addition',
    category: 'senior',
    description: '向量 a + b 平行四边形法则（拖动 A/B，C 联动）',
    descriptionEn: 'Parallelogram law — drag A/B, C follows',
    doc: {
      version: '1.0',
      viewport: { xmin: -1, xmax: 7, ymin: -1, ymax: 5 },
      elements: [
        { id: 'O', type: 'point', x: 0, y: 0, label: 'O', draggable: false },
        { id: 'A', type: 'point', x: 4, y: 1, label: 'A', draggable: true },
        { id: 'B', type: 'point', x: 2, y: 3, label: 'B', draggable: true },
        { id: 'parA', type: 'parallel', through: 'A', to: 'seg:O|B', auxiliary: true, style: 'dashed' },
        { id: 'parB', type: 'parallel', through: 'B', to: 'seg:O|A', auxiliary: true, style: 'dashed' },
        { id: 'C', type: 'intersection', of: ['parA', 'parB'], label: 'C' },
        { id: 'a', type: 'segment', between: ['O', 'A'], label: 'a' },
        { id: 'b', type: 'segment', between: ['O', 'B'], label: 'b' },
        { id: 'sum', type: 'segment', between: ['O', 'C'], label: 'a+b' },
        { id: 'par1', type: 'segment', between: ['A', 'C'], auxiliary: true, style: 'dashed' },
        { id: 'par2', type: 'segment', between: ['B', 'C'], auxiliary: true, style: 'dashed' },
      ],
    },
  },
  {
    id: 'derivative-tangent',
    name: '导数切线',
    nameEn: 'Derivative Tangent',
    category: 'senior',
    description: '拖动 P 沿 y=x²，切线随导数更新',
    descriptionEn: 'Drag P on y=x²; tangent follows the derivative',
    doc: {
      version: '1.0',
      viewport: { xmin: -3, xmax: 3, ymin: -1, ymax: 5 },
      elements: [
        { id: 'P', type: 'point', x: 1, y: 1, label: 'P', draggable: true, onFunction: 'f1' },
        { id: 'T', type: 'point', x: 2.2, y: 3.4, label: 'T', draggable: false, tangentFrom: 'P' },
        { id: 'tangent', type: 'line', through: ['P', 'T'], auxiliary: true, style: 'dashed' },
      ],
      functions: [{
        id: 'f1',
        expr: 'x^2',
        color: '#1C1C1E',
      }],
    },
  },
  {
    id: 'circumcircle',
    name: '三角形外接圆',
    nameEn: 'Circumcircle',
    category: 'senior',
    description: '外接圆与圆心',
    descriptionEn: 'Circumcircle and center',
    doc: {
      version: '1.0',
      viewport: { xmin: -2, xmax: 8, ymin: -3, ymax: 7 },
      elements: [
        { id: 'A', type: 'point', x: 1, y: 1, label: 'A', draggable: true },
        { id: 'B', type: 'point', x: 5, y: 1, label: 'B', draggable: true },
        { id: 'C', type: 'point', x: 3, y: 5, label: 'C', draggable: true },
        { id: 'tri', type: 'polygon', vertices: ['A', 'B', 'C'] },
        { id: 'cc', type: 'circumcircle', vertices: ['A', 'B', 'C'], auxiliary: true, style: 'dashed' },
      ],
    },
  },
  {
    id: 'isosceles-triangle',
    name: '等腰三角形',
    nameEn: 'Isosceles Triangle',
    category: 'junior',
    description: '等腰 △ABC，底边中线与顶角平分线重合',
    descriptionEn: 'Isosceles triangle with median/altitude',
    doc: {
      version: '1.0',
      viewport: { xmin: -1, xmax: 7, ymin: -1, ymax: 6 },
      elements: [
        { id: 'A', type: 'point', x: 1, y: 1, label: 'A', draggable: true },
        { id: 'B', type: 'point', x: 5, y: 1, label: 'B', draggable: true },
        { id: 'C', type: 'point', x: 3, y: 4.5, label: 'C', draggable: true },
        { id: 'tri', type: 'polygon', vertices: ['A', 'B', 'C'] },
        { id: 'M', type: 'midpoint', of: ['A', 'B'], label: 'M' },
        { id: 'CM', type: 'segment', between: ['C', 'M'], auxiliary: true, style: 'dashed' },
      ],
      annotations: [
        { type: 'distance', points: ['A', 'C'], label: 'AC' },
        { type: 'distance', points: ['B', 'C'], label: 'BC' },
        { type: 'angle', points: ['A', 'C', 'B'], label: '∠C' },
      ],
    },
  },
  {
    id: 'parallelogram',
    name: '平行四边形',
    nameEn: 'Parallelogram',
    category: 'junior',
    description: '平行四边形 ABCD 与对角线',
    descriptionEn: 'Parallelogram with diagonals',
    doc: {
      version: '1.0',
      viewport: { xmin: -1, xmax: 8, ymin: -1, ymax: 6 },
      elements: [
        { id: 'A', type: 'point', x: 1, y: 1, label: 'A', draggable: true },
        { id: 'B', type: 'point', x: 5, y: 1, label: 'B', draggable: true },
        { id: 'D', type: 'point', x: 2.5, y: 3.5, label: 'D', draggable: true },
        { id: 'parC', type: 'parallel', through: 'B', to: 'seg:A|D', auxiliary: true, style: 'dashed' },
        { id: 'parD', type: 'parallel', through: 'D', to: 'seg:A|B', auxiliary: true, style: 'dashed' },
        { id: 'C', type: 'intersection', of: ['parC', 'parD'], label: 'C' },
        { id: 'quad', type: 'polygon', vertices: ['A', 'B', 'C', 'D'] },
        { id: 'AC', type: 'segment', between: ['A', 'C'], auxiliary: true, style: 'dashed' },
        { id: 'BD', type: 'segment', between: ['B', 'D'], auxiliary: true, style: 'dashed' },
      ],
      annotations: [{ type: 'area', points: ['A', 'B', 'C', 'D'], label: 'S' }],
    },
  },
  {
    id: 'circle-chord-angle',
    name: '圆周角定理',
    nameEn: 'Inscribed Angle',
    category: 'junior',
    description: '同弧所对圆周角与圆心角',
    descriptionEn: 'Central vs inscribed angle on same arc',
    doc: {
      version: '1.0',
      viewport: { xmin: -4, xmax: 4, ymin: -4, ymax: 4 },
      elements: [
        { id: 'O', type: 'point', x: 0, y: 0, label: 'O', draggable: false },
        { id: 'A', type: 'point', x: 2.5, y: 0, label: 'A', draggable: true },
        { id: 'B', type: 'point', x: -1.2, y: 2.2, label: 'B', draggable: true },
        { id: 'C', type: 'point', x: -1.5, y: -2, label: 'C', draggable: true },
        { id: 'cir', type: 'circle', center: 'O', through: 'A' },
        { id: 'OA', type: 'segment', between: ['O', 'A'] },
        { id: 'OB', type: 'segment', between: ['O', 'B'] },
        { id: 'AB', type: 'segment', between: ['A', 'B'] },
        { id: 'AC', type: 'segment', between: ['A', 'C'] },
        { id: 'BC', type: 'segment', between: ['B', 'C'] },
      ],
      annotations: [
        { type: 'angle', points: ['A', 'O', 'B'], label: '圆心角' },
        { type: 'angle', points: ['A', 'C', 'B'], label: '圆周角' },
      ],
    },
  },
  {
    id: 'absolute-value',
    name: '绝对值函数',
    nameEn: 'Absolute Value',
    category: 'junior',
    description: 'y = |x| 与可拖动参数 k',
    descriptionEn: 'y = k|x| with draggable k',
    doc: {
      version: '1.0',
      viewport: { xmin: -5, xmax: 5, ymin: -1, ymax: 6 },
      elements: [{ id: 'k', type: 'point', x: 1.5, y: -0.5, label: 'k', draggable: true }],
      functions: [{ id: 'f1', expr: 'k*abs(x)', color: '#1C1C1E' }],
    },
  },
  {
    id: 'exponential',
    name: '指数函数',
    nameEn: 'Exponential',
    category: 'senior',
    description: 'y = a^x，拖动 a 观察增减性',
    descriptionEn: 'y = a^x — drag a to change growth',
    doc: {
      version: '1.0',
      viewport: { xmin: -3, xmax: 4, ymin: -1, ymax: 6 },
      elements: [{ id: 'a', type: 'point', x: 2, y: -0.6, label: 'a', draggable: true }],
      functions: [{ id: 'f1', expr: 'a^x', color: '#1C1C1E', domain: [-3, 4] }],
    },
  },
  {
    id: 'logarithmic',
    name: '对数函数',
    nameEn: 'Logarithm',
    category: 'senior',
    description: 'y = log(x)（自然对数）',
    descriptionEn: 'y = log(x) natural log',
    doc: {
      version: '1.0',
      viewport: { xmin: -1, xmax: 8, ymin: -3, ymax: 3 },
      elements: [],
      functions: [{ id: 'f1', expr: 'log(x)', color: '#1C1C1E', domain: [0.05, 8] }],
    },
  },
  {
    id: 'trig-unit-circle',
    name: '单位圆与三角函数',
    nameEn: 'Unit Circle',
    category: 'senior',
    description: '单位圆上点 P，观察坐标与角',
    descriptionEn: 'Point P on unit circle',
    doc: {
      version: '1.0',
      viewport: { xmin: -2.5, xmax: 2.5, ymin: -2.5, ymax: 2.5 },
      elements: [
        { id: 'O', type: 'point', x: 0, y: 0, label: 'O', draggable: false },
        { id: 'A', type: 'point', x: 1, y: 0, label: 'A', draggable: false },
        { id: 'P', type: 'point', x: 0.6, y: 0.8, label: 'P', draggable: true },
        { id: 'cir', type: 'circle', center: 'O', radius: 1 },
        { id: 'OP', type: 'segment', between: ['O', 'P'] },
        { id: 'Px', type: 'point', x: 0.6, y: 0, label: "P'", draggable: false },
        { id: 'drop', type: 'segment', between: ['P', 'Px'], auxiliary: true, style: 'dashed' },
      ],
      annotations: [
        { type: 'angle', points: ['A', 'O', 'P'], label: 'θ' },
        { type: 'distance', points: ['O', 'P'], label: 'r' },
      ],
    },
  },
  {
    id: 'linear-system',
    name: '二元一次方程组',
    nameEn: 'Linear System',
    category: 'junior',
    description: '两直线交点为方程组的解',
    descriptionEn: 'Intersection solves a linear system',
    doc: {
      version: '1.0',
      viewport: { xmin: -2, xmax: 6, ymin: -2, ymax: 6 },
      elements: [
        { id: 'A1', type: 'point', x: 0, y: 1, label: 'A1', draggable: true },
        { id: 'A2', type: 'point', x: 4, y: 3, label: 'A2', draggable: true },
        { id: 'B1', type: 'point', x: 0, y: 4, label: 'B1', draggable: true },
        { id: 'B2', type: 'point', x: 4, y: 0, label: 'B2', draggable: true },
        { id: 'l1', type: 'line', through: ['A1', 'A2'] },
        { id: 'l2', type: 'line', through: ['B1', 'B2'] },
        { id: 'S', type: 'intersection', of: ['l1', 'l2'], label: '解' },
      ],
      functions: [
        { id: 'f1', expr: '0.5*x + 1', color: '#1C1C1E', bind: { mode: 'linear', points: ['A1', 'A2'] } },
        { id: 'f2', expr: '-x + 4', color: '#8E8E93', bind: { mode: 'linear', points: ['B1', 'B2'] } },
      ],
    },
  },
  {
    id: 'inequality-region',
    name: '线性规划示意',
    nameEn: 'Feasible Region Hint',
    category: 'senior',
    description: '两条约束直线与可行区域示意点',
    descriptionEn: 'Constraint lines with a feasible sample point',
    doc: {
      version: '1.0',
      viewport: { xmin: -1, xmax: 7, ymin: -1, ymax: 6 },
      elements: [
        { id: 'A', type: 'point', x: 0, y: 4, label: 'A', draggable: true },
        { id: 'B', type: 'point', x: 4, y: 0, label: 'B', draggable: true },
        { id: 'C', type: 'point', x: 0, y: 0, label: 'O', draggable: false },
        { id: 'D', type: 'point', x: 5, y: 2, label: 'D', draggable: true },
        { id: 'l1', type: 'line', through: ['A', 'B'], auxiliary: true },
        { id: 'l2', type: 'line', through: ['C', 'D'], auxiliary: true },
        { id: 'P', type: 'point', x: 1.5, y: 1.2, label: 'P', draggable: true },
      ],
      annotations: [{ type: 'label', at: 'P', label: '可行点 P' }],
    },
  },
]
